### ISSUE TITLE
NApps are installed in old venv folder

### ISSUE THREAD

**Issue by cemsbr** [kytos/kytos-utils#85] opened 2017-05-12 20:48 UTC
```
# load new_virtualenv1
rm ~/.kytosrc
kytos napps install kytos/of_core
# a new ~/.kytosrc will be created
# load new_virtualenv2
# delete new_virtualenv1
kytos napps install kytos/of_core
kytos napps list
# NApp is installed in new_virtualenv1 folder
# NApp new_virtualenv2 NApps folder is empty
# NApp won't be loaded by kytosd in new_virtualenv2
```

The problem is that `~/.kytosrc` file keeps old entries for napps dirs.

**Comment by renanrodrigo** [comment] 2017-05-13 12:40
In a 'new' installation, `~/.kytosrc` is still the same, while (a new copy of) `/etc/kytos/kytos.conf` is installed on the detected `[BASE_ENV]`. The problem is both files contains a 'napps_dir' configuration.
`kytos-utils` uses the directory configured in `kytosrc` and `kytos` reads it from `kytos.conf`.

**Comment by beraldoleal** [comment] 2017-05-16 17:35
This will be fixed after #86

**Closed** 2017-06-12 17:23 UTC
Labels: status:pull-request
