### ISSUE TITLE
Error when creating a new NApp

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos-utils#190] opened 2018-09-16 21:55 UTC
Exact steps to reproduce:

1. Create a new python3.6 virtual environment and activate it
2. run `pip install kytos` (defaults to the 2018.1 version)
3. run `kytosd -f`
4. run `kytos napps create`
5. provide information about the NApp

Result:
```
Traceback (most recent call last):
  File "/home/user/venv/bin/kytos", line 43, in <module>
    parse(argv)
  File "/home/user/venv/lib/python3.6/site-packages/kytos/cli/commands/napps/parser.py", line 51, in parse
    call(sys.argv[2], args)
  File "/home/user/venv/lib/python3.6/site-packages/kytos/cli/commands/napps/parser.py", line 61, in call
    func(args)
  File "/home/user/venv/lib/python3.6/site-packages/kytos/cli/commands/napps/api.py", line 87, in create
    NAppsManager.create_napp()
  File "/home/user/venv/lib/python3.6/site-packages/kytos/utils/napps.py", line 415, in create_napp
    templates = os.listdir(templates_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/venv/etc/skel/kytos/napp-structure/username/napp'
```

**Comment by beraldoleal** [comment] 2018-09-17 15:46
Thanks, @renanrodrigo.

@macartur or @hdiogenes can you guys please, take a look into this?

**Comment by hdiogenes** [comment] 2018-10-09 20:31
Successfully reproduced. If you checkout the `kytos-utils` code and run `python setup.py develop` inside it, it'll fix the missing directory by symlink'ing it to a valid directory.

The  fix is to make `kytos-utils` copy it on the install (or when running `kytos napps create`, if the dir is still missing):
```
cp -r ${VIRTUAL_ENV}/src/kytos-utils/etc/skel/kytos \
      ${VIRTUAL_ENV}/etc/skel/kytos/napp-structure/username/napp
```

**Comment by renanrodrigo** [comment] 2018-10-09 21:56
Thanks a lot

**Comment by beraldoleal** [comment] 2018-10-11 13:08
@hdiogenes Cool. Can you provide a simple PR on kytos-utils, please?

**Comment by hdiogenes** [comment] 2018-10-15 14:21
Fixed by @macartur in #191.

**Comment by mhaji007** [comment] 2019-01-20 21:30
Hello,

I'm new to Kytos and I'm trying to learn by following the tutorials at https://tutorials.kytos.io/napps/create_your_napp/. I was wondering if this bug was fixed because I'm still getting this error while trying to create my very first NApp.

I'm running Ubuntu 18.04.1. 

Any insight is very much appreciated.

**Comment by beraldoleal** [comment] 2019-01-21 11:58
@mhaji007 welcome. And thanks to report this.

I'm reopening this in order to make more tests, to make sure that the bug is gone.

**Comment by beraldoleal** [comment] 2019-01-21 11:59
@hdiogenes can you please take a close look ?

**Comment by mhaji007** [comment] 2019-01-21 15:15
Thank you very much! I've been stuck at this stage for quite some time now
so I really appreciate you taking the time.

By the way, my name is Mehdi Hajikhani, I'm a senior majoring in
Computer Science at Florida International University (FIU). My teammate and
I will be collaborating with CIARA on the AmLight project as part of our
senior design. I was wondering if we could join you on slack to seek help
and guidance regarding Kytos and OpenFlow in general?

**Comment by beraldoleal** [comment] 2019-01-21 15:17
Hi @mhaji007 , thats awesome. Jeronimo told me about that.

Of course you can. Please feel free to join and share the link:

https://join.slack.com/t/kytos/shared_invite/enQtMjk0MTM0NjQwOTE1LTkzODE2YTQ3NTQ0MGRlYzcyNTZjYjQ4Yjc2NmI5NWZmNmMxNjNiOTVkOTE0YTQwN2Q2NjZjNDkwODM5OWRjNGY

**Closed** 2019-01-23 20:10 UTC
Labels: bug, pri:high
